#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint staged files
npx lint-staged

# prevent committing directly to main/master
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "You can't commit directly to $branch branch. Please create a branch and use a pull request."
  exit 1
fi
